from django.conf.urls import url
from condos import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^guide/$', views.GuideView.as_view(), name='guide'),
    url(r'^condos/kihei-kai-nani/$', views.KiheiKaiNaniView.as_view(), name='kkn'),
    url(r'^condos/pacific-shores/$', views.PacificShoresView.as_view(), name='pacific_shores'),
    url(r'^guide/beaches/$', views.BeachesView.as_view(), name='beaches'),
    url(r'^guide/beaches/south-maui/$', views.SouthMauiView.as_view(), name='south_maui_beaches'),
    url(r'^guide/beaches/south-maui/kamaole-beaches/$', views.KamaoleBeachesView.as_view(), name='kamaole_beaches'),
    url(r'^guide/beaches/south-maui/kalama-park/$', views.KalamaParkView.as_view(), name='kalama_park'),
    url(r'^guide/beaches/south-maui/keawakapu-beach/$', views.KeawakapuView.as_view(), name='keawakapu'),
    url(r'^guide/beaches/south-maui/ulua-beach/$', views.UluaView.as_view(), name='ulua'),
    url(r'^guide/beaches/south-maui/wailea-beach/$', views.WaileaView.as_view(), name='wailea'),
    url(r'^guide/beaches/south-maui/palauea-beach/$', views.PalaueaView.as_view(), name='palauea'),
    url(r'^guide/beaches/south-maui/poolenalena-beach/$', views.PoolenalenaView.as_view(), name='poolenalena'),
    url(r'^guide/beaches/south-maui/maluaka-beach/$', views.MaluakaView.as_view(), name='maluaka'),
    url(r'^guide/beaches/south-maui/big-beach/$', views.BigBeachView.as_view(), name='big_beach'),
    url(r'^guide/beaches/west-maui/$', views.WestMauiBeachesView.as_view(), name='west_maui_beaches'),
    url(r'^guide/beaches/west-maui/kaanapali-beach/$', views.KaanapaliBeachView.as_view(), name='kaanapali_beach'),
    url(r'^guide/beaches/west-maui/napili-bay/$', views.NapiliBayView.as_view(), name='napili_bay'),
    url(r'^guide/beaches/west-maui/kapalua-bay/$', views.KapaluaBayView.as_view(), name='kapalua_bay'),
    url(r'^guide/beaches/west-maui/honolua-bay/$', views.HonoluaBayView.as_view(), name='honolua_bay'),
    url(r'^bguide/eaches/west-maui/baby-beach/$', views.BabyBeachView.as_view(), name='baby_beach'),
    url(r'^guide/beaches/north-maui/$', views.NorthMauiBeachesView.as_view(), name='north_maui_beaches'),
    url(r'^activities/$', views.ActivitiesView.as_view(), name='activities'),
    url(r'^activities/old-lahaina-luau/$', views.OldLahainaLuauView.as_view(), name='old_lahaina_luau'),
    url(r'^activities/whale-watching/$', views.WhaleWatchingView.as_view(), name='whale_watching'),
    url(r'^activities/maui-ocean-center-and-aquarium/$', views.AquariumView.as_view(), name='aquarium'),
    url(r'^activities/haleakala/$', views.HaleakalaView.as_view(), name='haleakala'),
    url(r'^activities/snorkeling/$', views.SnorkelingView.as_view(), name='snorkeling'),
    url(r'^activities/drive-to-hana/$', views.DriveToHanaView.as_view(), name='drive_to_hana'),
    url(r'^beaches/activities/la-perouse-bay/$', views.LaPerouseBayView.as_view(), name='la_perouse_bay'),
    url(r'^activities/maui-friday-town-parties/$', views.MauiFridayTownPartiesView.as_view(), name='maui_friday_town_parties'),
    url(r'^activities/alii-kula-lavendar-farm/$', views.AliiKulaLavendarFarmView.as_view(), name='alii_kula_lavendar_farm'),
    url(r'^places-to-eat/$', views.PlacesToEatView.as_view(), name='places_to_eat'),
    url(r'^places-to-eat/kihei-restaurants/$', views.KiheiRestaurantsView.as_view(), name='kihei_restaurants'),
    url(r'^places-to-eat/lahaina-restaurants/$', views.LahainaRestaurantsView.as_view(), name='lahaina_restaurants'),
    url(r'^places-to-eat/kaanapali-restaurants/$', views.KaanapaliRestaurantsView.as_view(), name='kaanapali_restaurants'),
    url(r'^places-to-eat/paia-restaurants/$', views.PaiaRestaurantsView.as_view(), name='paia_restaurants'),
    url(r'^more-maui-info/$', views.MoreMauiInfoView.as_view(), name='more_maui_info'),
    url(r'^more-maui-info/groceries/$', views.GroceriesView.as_view(), name='groceries'),
    url(r'^contact-us/$', views.ContactView.as_view(), name='contact'),

]
